openapi: 3.0.3
info:
  title: Modul 294 LB B Backend
  version: 1.0.11
servers:
  - url: http://localhost:3000
paths:
  /tasks:
    get:
      tags:
        - task
      summary: list all tasks
      description: List all tasks
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"
        "403":
          description: Unauthorized
    put:
      tags:
        - task
      summary: Update an existing task
      description: Update an existing task by Id
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task"
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        "400":
          description: Invalid ID supplied
        "403":
          description: Unauthorized
        "404":
          description: Task not found
        "405":
          description: Validation exception
    post:
      tags:
        - task
      summary: Add a new task
      description: Add a new task
      requestBody:
        description: Create a new task
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task"
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        "403":
          description: Unauthorized
        "405":
          description: Invalid input
  /task/{taskId}:
    get:
      tags:
        - task
      summary: Find task by ID
      description: Returns a single task
      operationId: getTaskById
      parameters:
        - name: taskId
          in: path
          description: ID of task to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        "400":
          description: Invalid ID supplied
        "403":
          description: Unauthorized
        "404":
          description: Task not found
    delete:
      tags:
        - task
      summary: Deletes a task
      description: delete a task
      parameters:
        - name: taskId
          in: path
          description: Task id to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "400":
          description: Invalid task value
        "403":
          description: Unauthorized
  /user/login:
    get:
      tags:
        - user
      summary: Logs user into the system
      description: ""
      parameters:
        - name: username
          in: query
          description: The user name for login
          required: false
          schema:
            type: string
        - name: password
          in: query
          description: The password for login in clear text
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: string
        "400":
          description: Invalid username/password supplied
  /user/logout:
    get:
      tags:
        - user
      summary: Logs out current logged in user session
      description: ""
      parameters: []
      responses:
        default:
          description: successful operation

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        completed:
          type: boolean
          example: false
        title:
          type: string
          example: "Feed pets"
  requestBodies:
    Task:
      description: Task object that needs to be added to the list
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Task"
        application/xml:
          schema:
            $ref: "#/components/schemas/Task"
